version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      SA_PASSWORD: "P@ssw0rd12"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"